In [1]:
# !pip install scikit-learn

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('emi_prediction_dataset.csv')

/var/folders/33/6j7x5yjn4vs9rpp5_xx32x740000gn/T/ipykernel_16831/1110627768.py:1: DtypeWarning: Columns (0: age) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('emi_prediction_dataset.csv')

In [4]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  object
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               402396 non-null  str
 4   monthly_salary          404800 non-null  str
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            402374 non-null  str
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(12), int64(3), object(1), str(11)
memory usage: 83.4+ MB

In [6]:
df.isnull().sum()

age                          0
gender                       0
marital_status               0
education                 2404
monthly_salary               0
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2426
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2420
bank_balance              2426
emergency_fund            2351
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

### fixing age Column

In [7]:
import re
df['age'] = df['age'].astype(str)
df['age'] = df['age'].str.replace(r'\.0+', '', regex=True)
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].astype(int)

In [8]:
df['gender'].value_counts()

gender
Male      237427
Female    158351
MALE        1865
M           1843
male        1815
F           1171
female      1165
FEMALE      1163
Name: count, dtype: int64

### Fixing Gender column

In [9]:
gender_dict={
    'Male':'M',
    'MALE':'M',
    'male':'M',
    'Female':'F',
    'female':'F',
    'FEMALE':'F'
}
df['gender']=df['gender'].replace(gender_dict)

In [10]:
df['marital_status'].value_counts()

marital_status
Married    307837
Single      96963
Name: count, dtype: int64

In [11]:
df['education'].value_counts()

education
Graduate         181015
Post Graduate    100314
High School       60732
Professional      60335
Name: count, dtype: int64

In [12]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38,F,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38,F,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38,M,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58,F,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48,F,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

### fixing education column filling na with unknown

In [13]:
df['education']=df['education'].fillna('Unknown')

### Fixing Column monthly_salary

In [14]:
df['monthly_salary']=df['monthly_salary'].astype(str)
df['monthly_salary']=df['monthly_salary'].str.replace(r'\.0+', '', regex=True)
df['monthly_salary']=pd.to_numeric(df['monthly_salary'])

In [15]:
df['monthly_salary'].dtype

dtype('int64')

In [16]:
df['employment_type'].value_counts()

employment_type
Private          283099
Government        81167
Self-employed     40534
Name: count, dtype: int64

In [17]:
df['company_type'].value_counts()

company_type
Large Indian    121139
MNC             101409
Mid-size        101301
Startup          60706
Small            20245
Name: count, dtype: int64

In [18]:
df['house_type'].value_counts()

house_type
Rented    161601
Own       142307
Family    100892
Name: count, dtype: int64

In [19]:
df[(df['house_type'].isin(['Own','Family'])) & (df['monthly_rent']>0)]

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
51,32,F,Married,High School,17700,Private,3.0,Mid-size,Own,16224.0,...,Yes,3200.0,700.0,36600.0,14300.0,Vehicle EMI,1284000.0,55,Not_Eligible,2590.00
130,58,F,Married,Post Graduate,36700,Private,14.0,Large Indian,Own,24407.0,...,Yes,5500.0,721.0,82600.0,27900.0,Education EMI,382000.0,33,Not_Eligible,500.00
154,27,M,Married,Professional,63700,Private,4.2,MNC,Own,7917.0,...,Yes,16700.0,NaN,320700.0,173600.0,Home Appliances EMI,103000.0,7,Not_Eligible,3955.00
191,38,F,Married,High School,76000,Private,0.6,Small,Family,6843.0,...,Yes,18000.0,588.0,51100.0,16200.0,Personal Loan EMI,82000.0,57,Not_Eligible,1648.64
220,32,F,Single,Post Graduate,41200,Government,2.3,Mid-size,Family,13983.0,...,No,0.0,768.0,187300.0,49800.0,Home Appliances EMI,273000.0,16,Not_Eligible,14340.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403920,27,M,Single,Post Graduate,96200,Private,0.5,Startup,Family,21554.0,...,No,0.0,698.0,480000.0,98400.0,Personal Loan EMI,873000.0,17,Not_Eligible,23440.00
403959,38,F,Married,Professional,85800,Self-employed,0.5,Startup,Family,9404.0,...,No,0.0,661.0,461000.0,212600.0,Personal Loan EMI,124000.0,44,Eligible,17595.00
404034,32,M,Married,Graduate,80600,Private,1.7,Large Indian,Own,9109.0,...,No,0.0,775.0,279300.0,74600.0,Education EMI,339000.0,39,Eligible,30000.00
404712,38,M,Married,Post Graduate,61500,Government,3.7,Large Indian,Own,6143.0,...,No,0.0,782.0,36200.0,20700.0,Home Appliances EMI,72000.0,23,Eligible,16948.80
404755,58,F,Married,Graduate,36500,Government,4.1,Large Indian,Own,8366.0,...,Yes,10300.0,693.0,285000.0,145800.0,Education EMI,363000.0,28,Not_Eligible,1228.15

### Fxing Monthly_rent column imputed it with median(0)

In [20]:
df['monthly_rent']=df['monthly_rent'].fillna(df['monthly_rent'].median())

### removed anomalies and nulls from credit_score

In [21]:
df=df[
    (df['credit_score'].between(300,850))&
    (df['credit_score'].notnull())
]

In [22]:
df.shape

(397604, 27)

-- standardizing bank_balance

In [23]:
df['bank_balance']=df['bank_balance'].astype(str)
df['bank_balance']=df['bank_balance'].str.replace(r'\.0+', '', regex=True)
df['bank_balance']=pd.to_numeric(df['bank_balance'],errors='coerce')

In [24]:
df['bank_balance'].isnull().sum()

np.int64(2394)

### as bank balance is strongly related to our target so we are dropping rows

In [25]:
df=df[df['bank_balance'].notnull()]

In [26]:
df=df[df['emergency_fund'].notnull()]

In [27]:
df['emi_scenario'].value_counts()

emi_scenario
Personal Loan EMI          78632
Vehicle EMI                78597
Education EMI              78576
Home Appliances EMI        78557
E-commerce Shopping EMI    78542
Name: count, dtype: int64

In [28]:
df['requested_tenure'].max()

np.int64(84)

In [29]:
df.to_csv('emi_cleaned.csv',index=False)

In [30]:
df1=pd.read_csv('emi_cleaned.csv')

In [31]:
df1.shape

(392904, 27)

In [32]:
df1.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38,F,Married,Professional,82600,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38,F,Married,Graduate,21500,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38,M,Married,Professional,86100,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58,F,Married,High School,66800,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48,F,Married,Professional,57300,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0